version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      - mongo
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-net

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
    name: sorteio_net