version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  mongo_data: